// ModLoader_Defines.h — human names for all labels/statics
// Generated by tools/generate_naming.py — do not edit manually
// Include in your CSA via: IncludeStaticFile ModLoader_Defines.h  // or just use as reference

#pragma once

// ---------- Labels (Functions) ----------
#define Mod_Init_Main  Label_0  // call via Call @Mod_Init_Main or :Mod_Init_Main
#define Mod_Init_TexturesAndLocals  Label_1  // call via Call @Mod_Init_TexturesAndLocals or :Mod_Init_TexturesAndLocals
#define Page_JakeModz_Invisible_Impl  Label_100  // call via Call @Page_JakeModz_Invisible_Impl or :Page_JakeModz_Invisible_Impl
#define Page_IvoAlqaedaMale_Impl  Label_101  // call via Call @Page_IvoAlqaedaMale_Impl or :Page_IvoAlqaedaMale_Impl
#define Page_StaticText_Label_1012  Label_1012  // call via Call @Page_StaticText_Label_1012 or :Page_StaticText_Label_1012
#define Page_StaticText_Label_1019  Label_1019  // call via Call @Page_StaticText_Label_1019 or :Page_StaticText_Label_1019
#define Page_IvoFemaleOutfits_Impl  Label_102  // call via Call @Page_IvoFemaleOutfits_Impl or :Page_IvoFemaleOutfits_Impl
#define Page_MainsMods_PlayerOptions_Impl  Label_103  // call via Call @Page_MainsMods_PlayerOptions_Impl or :Page_MainsMods_PlayerOptions_Impl
#define Page_StaticText_Label_1039  Label_1039  // call via Call @Page_StaticText_Label_1039 or :Page_StaticText_Label_1039
#define Page_WeaponsOptions_Impl  Label_104  // call via Call @Page_WeaponsOptions_Impl or :Page_WeaponsOptions_Impl
#define Page_VehicleOptions_Impl  Label_105  // call via Call @Page_VehicleOptions_Impl or :Page_VehicleOptions_Impl
#define Page_StaticText_Label_1056  Label_1056  // call via Call @Page_StaticText_Label_1056 or :Page_StaticText_Label_1056
#define Page_VehicleSpawner_Impl  Label_106  // call via Call @Page_VehicleSpawner_Impl or :Page_VehicleSpawner_Impl
#define Page_SpawningSettings_Impl  Label_107  // call via Call @Page_SpawningSettings_Impl or :Page_SpawningSettings_Impl
#define Page_StaticText_Label_1071  Label_1071  // call via Call @Page_StaticText_Label_1071 or :Page_StaticText_Label_1071
#define Page_SpriteToggle_Impl  Label_108  // call via Call @Page_SpriteToggle_Impl or :Page_SpriteToggle_Impl
#define Page_Settings_VerticalScrollbar_Impl  Label_109  // call via Call @Page_Settings_VerticalScrollbar_Impl or :Page_Settings_VerticalScrollbar_Impl
#define Page_StaticText_Label_1102  Label_1102  // call via Call @Page_StaticText_Label_1102 or :Page_StaticText_Label_1102
#define Func_Label_111  Label_111  // call via Call @Func_Label_111 or :Func_Label_111
#define Page_StaticText_Label_1114  Label_1114  // call via Call @Page_StaticText_Label_1114 or :Page_StaticText_Label_1114
#define Tick_HandleInput__SkipIfMenuOpen  Label_112  // call via Call @Tick_HandleInput__SkipIfMenuOpen or :Tick_HandleInput__SkipIfMenuOpen
#define Tick_HandleInput__Check132  Label_113  // call via Call @Tick_HandleInput__Check132 or :Tick_HandleInput__Check132
#define Page_StaticText_Label_1133  Label_1133  // call via Call @Page_StaticText_Label_1133 or :Page_StaticText_Label_1133
#define Tick_HandleInput__Set133  Label_114  // call via Call @Tick_HandleInput__Set133 or :Tick_HandleInput__Set133
#define UI_Calc_VisibleRows  Label_1151  // call via Call @UI_Calc_VisibleRows or :UI_Calc_VisibleRows
#define UI_Text_Label_1152  Label_1152  // call via Call @UI_Text_Label_1152 or :UI_Text_Label_1152
#define UI_Text_Label_1153  Label_1153  // call via Call @UI_Text_Label_1153 or :UI_Text_Label_1153
#define UI_Draw_HeaderTitle  Label_1154  // call via Call @UI_Draw_HeaderTitle or :UI_Draw_HeaderTitle
#define Func_Label_1155  Label_1155  // call via Call @Func_Label_1155 or :Func_Label_1155
#define Util_LangPick_4Str  Label_1156  // call via Call @Util_LangPick_4Str or :Util_LangPick_4Str
#define Func_Label_1157  Label_1157  // call via Call @Func_Label_1157 or :Func_Label_1157
#define UI_Handle_Scroll  Label_1158  // call via Call @UI_Handle_Scroll or :UI_Handle_Scroll
#define UI_Handle_MenuSelect  Label_1163  // call via Call @UI_Handle_MenuSelect or :UI_Handle_MenuSelect
#define Func_Label_1166  Label_1166  // call via Call @Func_Label_1166 or :Func_Label_1166
#define Page_StaticText_Label_1168  Label_1168  // call via Call @Page_StaticText_Label_1168 or :Page_StaticText_Label_1168
#define Page_StaticText_Label_1169  Label_1169  // call via Call @Page_StaticText_Label_1169 or :Page_StaticText_Label_1169
#define UI_Draw_ToggleRow  Label_1170  // call via Call @UI_Draw_ToggleRow or :UI_Draw_ToggleRow
#define Func_Label_1179  Label_1179  // call via Call @Func_Label_1179 or :Func_Label_1179
#define Func_Label_1181  Label_1181  // call via Call @Func_Label_1181 or :Func_Label_1181
#define Func_Label_119  Label_119  // call via Call @Func_Label_119 or :Func_Label_119
#define Teleport_Do_Label_1239  Label_1239  // call via Call @Teleport_Do_Label_1239 or :Teleport_Do_Label_1239
#define Func_Label_1240  Label_1240  // call via Call @Func_Label_1240 or :Func_Label_1240
#define Func_Label_1241  Label_1241  // call via Call @Func_Label_1241 or :Func_Label_1241
#define Func_Label_1283  Label_1283  // call via Call @Func_Label_1283 or :Func_Label_1283
#define UI_Text_Label_1319  Label_1319  // call via Call @UI_Text_Label_1319 or :UI_Text_Label_1319
#define Func_Label_1361  Label_1361  // call via Call @Func_Label_1361 or :Func_Label_1361
#define Func_Label_1362  Label_1362  // call via Call @Func_Label_1362 or :Func_Label_1362
#define Func_Label_1363  Label_1363  // call via Call @Func_Label_1363 or :Func_Label_1363
#define Func_Label_1364  Label_1364  // call via Call @Func_Label_1364 or :Func_Label_1364
#define Func_Label_1365  Label_1365  // call via Call @Func_Label_1365 or :Func_Label_1365
#define Func_Label_1366  Label_1366  // call via Call @Func_Label_1366 or :Func_Label_1366
#define Func_Label_1367  Label_1367  // call via Call @Func_Label_1367 or :Func_Label_1367
#define Func_Label_1368  Label_1368  // call via Call @Func_Label_1368 or :Func_Label_1368
#define Func_Label_1369  Label_1369  // call via Call @Func_Label_1369 or :Func_Label_1369
#define Func_Label_1370  Label_1370  // call via Call @Func_Label_1370 or :Func_Label_1370
#define Func_Label_1371  Label_1371  // call via Call @Func_Label_1371 or :Func_Label_1371
#define Func_Label_1372  Label_1372  // call via Call @Func_Label_1372 or :Func_Label_1372
#define Func_Label_1373  Label_1373  // call via Call @Func_Label_1373 or :Func_Label_1373
#define Func_Label_1374  Label_1374  // call via Call @Func_Label_1374 or :Func_Label_1374
#define Func_Label_1375  Label_1375  // call via Call @Func_Label_1375 or :Func_Label_1375
#define Func_Label_1376  Label_1376  // call via Call @Func_Label_1376 or :Func_Label_1376
#define Func_Label_1377  Label_1377  // call via Call @Func_Label_1377 or :Func_Label_1377
#define Func_Label_1378  Label_1378  // call via Call @Func_Label_1378 or :Func_Label_1378
#define Func_Label_1379  Label_1379  // call via Call @Func_Label_1379 or :Func_Label_1379
#define Func_Label_1380  Label_1380  // call via Call @Func_Label_1380 or :Func_Label_1380
#define Func_Label_1381  Label_1381  // call via Call @Func_Label_1381 or :Func_Label_1381
#define Func_Label_1382  Label_1382  // call via Call @Func_Label_1382 or :Func_Label_1382
#define Entity_GetClosestObjectInFront  Label_145  // call via Call @Entity_GetClosestObjectInFront or :Entity_GetClosestObjectInFront
#define Vehicle_Spawn_ByHash  Label_1509  // call via Call @Vehicle_Spawn_ByHash or :Vehicle_Spawn_ByHash
#define Util_LangPick_ES_EN  Label_163  // call via Call @Util_LangPick_ES_EN or :Util_LangPick_ES_EN
#define Func_Label_164  Label_164  // call via Call @Func_Label_164 or :Func_Label_164
#define Func_Label_167  Label_167  // call via Call @Func_Label_167 or :Func_Label_167
#define Func_Label_169  Label_169  // call via Call @Func_Label_169 or :Func_Label_169
#define Func_Label_171  Label_171  // call via Call @Func_Label_171 or :Func_Label_171
#define Func_Label_173  Label_173  // call via Call @Func_Label_173 or :Func_Label_173
#define Loader_AddMenuEntry  Label_1835  // call via Call @Loader_AddMenuEntry or :Loader_AddMenuEntry
#define Page_StaticText_Label_1844  Label_1844  // call via Call @Page_StaticText_Label_1844 or :Page_StaticText_Label_1844
#define Func_Label_1845  Label_1845  // call via Call @Func_Label_1845 or :Func_Label_1845
#define Page_StaticText_Label_1846  Label_1846  // call via Call @Page_StaticText_Label_1846 or :Page_StaticText_Label_1846
#define Func_Label_1847  Label_1847  // call via Call @Func_Label_1847 or :Func_Label_1847
#define Func_Label_1915  Label_1915  // call via Call @Func_Label_1915 or :Func_Label_1915
#define Func_Label_1916  Label_1916  // call via Call @Func_Label_1916 or :Func_Label_1916
#define Func_Label_1940  Label_1940  // call via Call @Func_Label_1940 or :Func_Label_1940
#define Func_Label_1942  Label_1942  // call via Call @Func_Label_1942 or :Func_Label_1942
#define Page_StaticText_Label_1964  Label_1964  // call via Call @Page_StaticText_Label_1964 or :Page_StaticText_Label_1964
#define Func_Label_1966  Label_1966  // call via Call @Func_Label_1966 or :Func_Label_1966
#define Func_Label_198  Label_198  // call via Call @Func_Label_198 or :Func_Label_198
#define Func_Label_1988  Label_1988  // call via Call @Func_Label_1988 or :Func_Label_1988
#define Func_Label_1989  Label_1989  // call via Call @Func_Label_1989 or :Func_Label_1989
#define Func_Label_199  Label_199  // call via Call @Func_Label_199 or :Func_Label_199
#define Util_GetSafeZoneHalf  Label_2  // call via Call @Util_GetSafeZoneHalf or :Util_GetSafeZoneHalf
#define Func_Label_2084  Label_2084  // call via Call @Func_Label_2084 or :Func_Label_2084
#define Weapon_Give_Label_219  Label_219  // call via Call @Weapon_Give_Label_219 or :Weapon_Give_Label_219
#define Func_Label_220  Label_220  // call via Call @Func_Label_220 or :Func_Label_220
#define Func_Label_227  Label_227  // call via Call @Func_Label_227 or :Func_Label_227
#define Page_StaticText_Label_2276  Label_2276  // call via Call @Page_StaticText_Label_2276 or :Page_StaticText_Label_2276
#define Func_Label_2277  Label_2277  // call via Call @Func_Label_2277 or :Func_Label_2277
#define Func_Label_2278  Label_2278  // call via Call @Func_Label_2278 or :Func_Label_2278
#define Func_Label_2279  Label_2279  // call via Call @Func_Label_2279 or :Func_Label_2279
#define Func_Label_2280  Label_2280  // call via Call @Func_Label_2280 or :Func_Label_2280
#define Page_StaticText_Label_2281  Label_2281  // call via Call @Page_StaticText_Label_2281 or :Page_StaticText_Label_2281
#define Func_Label_2282  Label_2282  // call via Call @Func_Label_2282 or :Func_Label_2282
#define Page_StaticText_Label_2314  Label_2314  // call via Call @Page_StaticText_Label_2314 or :Page_StaticText_Label_2314
#define Func_Label_2315  Label_2315  // call via Call @Func_Label_2315 or :Func_Label_2315
#define Page_StaticText_Label_2317  Label_2317  // call via Call @Page_StaticText_Label_2317 or :Page_StaticText_Label_2317
#define Func_Label_2324  Label_2324  // call via Call @Func_Label_2324 or :Func_Label_2324
#define Func_Label_2325  Label_2325  // call via Call @Func_Label_2325 or :Func_Label_2325
#define UI_Draw_Label_2326  Label_2326  // call via Call @UI_Draw_Label_2326 or :UI_Draw_Label_2326
#define Page_StaticText_Label_2327  Label_2327  // call via Call @Page_StaticText_Label_2327 or :Page_StaticText_Label_2327
#define Func_Label_2342  Label_2342  // call via Call @Func_Label_2342 or :Func_Label_2342
#define Func_Label_2357  Label_2357  // call via Call @Func_Label_2357 or :Func_Label_2357
#define Page_StaticText_Label_2381  Label_2381  // call via Call @Page_StaticText_Label_2381 or :Page_StaticText_Label_2381
#define Func_Label_2382  Label_2382  // call via Call @Func_Label_2382 or :Func_Label_2382
#define Func_Label_2386  Label_2386  // call via Call @Func_Label_2386 or :Func_Label_2386
#define Func_Label_2414  Label_2414  // call via Call @Func_Label_2414 or :Func_Label_2414
#define Vehicle_Tuning_Label_2435  Label_2435  // call via Call @Vehicle_Tuning_Label_2435 or :Vehicle_Tuning_Label_2435
#define Vehicle_Tuning_Label_2436  Label_2436  // call via Call @Vehicle_Tuning_Label_2436 or :Vehicle_Tuning_Label_2436
#define Func_Label_2437  Label_2437  // call via Call @Func_Label_2437 or :Func_Label_2437
#define Vehicle_Tuning_Label_2438  Label_2438  // call via Call @Vehicle_Tuning_Label_2438 or :Vehicle_Tuning_Label_2438
#define Vehicle_Tuning_Label_2439  Label_2439  // call via Call @Vehicle_Tuning_Label_2439 or :Vehicle_Tuning_Label_2439
#define Func_Label_2442  Label_2442  // call via Call @Func_Label_2442 or :Func_Label_2442
#define Func_Label_2449  Label_2449  // call via Call @Func_Label_2449 or :Func_Label_2449
#define Func_Label_2452  Label_2452  // call via Call @Func_Label_2452 or :Func_Label_2452
#define Util_EnsureTextureDict  Label_2455  // call via Call @Util_EnsureTextureDict or :Util_EnsureTextureDict
#define Func_Label_255  Label_255  // call via Call @Func_Label_255 or :Func_Label_255
#define Func_Label_260  Label_260  // call via Call @Func_Label_260 or :Func_Label_260
#define Func_Label_262  Label_262  // call via Call @Func_Label_262 or :Func_Label_262
#define Util_ConcatStrings_ToBuffer  Label_263  // call via Call @Util_ConcatStrings_ToBuffer or :Util_ConcatStrings_ToBuffer
#define Func_Label_264  Label_264  // call via Call @Func_Label_264 or :Func_Label_264
#define Func_Label_267  Label_267  // call via Call @Func_Label_267 or :Func_Label_267
#define Func_Label_272  Label_272  // call via Call @Func_Label_272 or :Func_Label_272
#define Func_Label_275  Label_275  // call via Call @Func_Label_275 or :Func_Label_275
#define Func_Label_279  Label_279  // call via Call @Func_Label_279 or :Func_Label_279
#define Sfx_Play_ClickSpecial  Label_283  // call via Call @Sfx_Play_ClickSpecial or :Sfx_Play_ClickSpecial
#define Sfx_Play_MiniGame  Label_285  // call via Call @Sfx_Play_MiniGame or :Sfx_Play_MiniGame
#define Func_Label_291  Label_291  // call via Call @Func_Label_291 or :Func_Label_291
#define Sfx_Play_FrontendDefault  Label_298  // call via Call @Sfx_Play_FrontendDefault or :Sfx_Play_FrontendDefault
#define Main_Tick  Label_3  // call via Call @Main_Tick or :Main_Tick
#define UI_Set_HudColour  Label_314  // call via Call @UI_Set_HudColour or :UI_Set_HudColour
#define Func_Label_319  Label_319  // call via Call @Func_Label_319 or :Func_Label_319
#define Func_Label_320  Label_320  // call via Call @Func_Label_320 or :Func_Label_320
#define Func_Label_324  Label_324  // call via Call @Func_Label_324 or :Func_Label_324
#define Func_Label_326  Label_326  // call via Call @Func_Label_326 or :Func_Label_326
#define UI_Draw_Sprite  Label_327  // call via Call @UI_Draw_Sprite or :UI_Draw_Sprite
#define UI_Set_TextColorFromStatic  Label_331  // call via Call @UI_Set_TextColorFromStatic or :UI_Set_TextColorFromStatic
#define Func_Label_335  Label_335  // call via Call @Func_Label_335 or :Func_Label_335
#define UI_ClearTemp  Label_344  // call via Call @UI_ClearTemp or :UI_ClearTemp
#define UI_BeginDraw  Label_345  // call via Call @UI_BeginDraw or :UI_BeginDraw
#define UI_EndDraw  Label_346  // call via Call @UI_EndDraw or :UI_EndDraw
#define Func_Label_352  Label_352  // call via Call @Func_Label_352 or :Func_Label_352
#define Func_Label_355  Label_355  // call via Call @Func_Label_355 or :Func_Label_355
#define Func_Label_356  Label_356  // call via Call @Func_Label_356 or :Func_Label_356
#define Input_GetSelectedIndex  Label_358  // call via Call @Input_GetSelectedIndex or :Input_GetSelectedIndex
#define Func_Label_361  Label_361  // call via Call @Func_Label_361 or :Func_Label_361
#define Func_Label_362  Label_362  // call via Call @Func_Label_362 or :Func_Label_362
#define UI_Text_Label_363  Label_363  // call via Call @UI_Text_Label_363 or :UI_Text_Label_363
#define UI_Text_Label_364  Label_364  // call via Call @UI_Text_Label_364 or :UI_Text_Label_364
#define Func_Label_365  Label_365  // call via Call @Func_Label_365 or :Func_Label_365
#define Func_Label_367  Label_367  // call via Call @Func_Label_367 or :Func_Label_367
#define Func_Label_369  Label_369  // call via Call @Func_Label_369 or :Func_Label_369
#define Page_StaticText_Label_370  Label_370  // call via Call @Page_StaticText_Label_370 or :Page_StaticText_Label_370
#define Func_Label_377  Label_377  // call via Call @Func_Label_377 or :Func_Label_377
#define Func_Label_389  Label_389  // call via Call @Func_Label_389 or :Func_Label_389
#define UI_Draw_TextRow  Label_396  // call via Call @UI_Draw_TextRow or :UI_Draw_TextRow
#define Input_IsConfirmPressed  Label_397  // call via Call @Input_IsConfirmPressed or :Input_IsConfirmPressed
#define Func_Label_399  Label_399  // call via Call @Func_Label_399 or :Func_Label_399
#define Func_Label_400  Label_400  // call via Call @Func_Label_400 or :Func_Label_400
#define Func_Label_401  Label_401  // call via Call @Func_Label_401 or :Func_Label_401
#define Func_Label_402  Label_402  // call via Call @Func_Label_402 or :Func_Label_402
#define UI_Update_HighlightRect  Label_418  // call via Call @UI_Update_HighlightRect or :UI_Update_HighlightRect
#define Loader_AddMenuEntry__NotFoundBranch  Label_423  // call via Call @Loader_AddMenuEntry__NotFoundBranch or :Loader_AddMenuEntry__NotFoundBranch
#define Loader_AddMenuEntry__PS3Suffix  Label_424  // call via Call @Loader_AddMenuEntry__PS3Suffix or :Loader_AddMenuEntry__PS3Suffix
#define Loader_AddMenuEntry__AppendSuffix  Label_425  // call via Call @Loader_AddMenuEntry__AppendSuffix or :Loader_AddMenuEntry__AppendSuffix
#define Loader_AddMenuEntry__Return  Label_426  // call via Call @Loader_AddMenuEntry__Return or :Loader_AddMenuEntry__Return
#define UI_Draw_IconPlus  Label_427  // call via Call @UI_Draw_IconPlus or :UI_Draw_IconPlus
#define Loader_AddMenuEntry__Queue  Label_428  // call via Call @Loader_AddMenuEntry__Queue or :Loader_AddMenuEntry__Queue
#define Input_IsConfirmPressed__ReturnFalse  Label_432  // call via Call @Input_IsConfirmPressed__ReturnFalse or :Input_IsConfirmPressed__ReturnFalse
#define UI_Update_Highlight__CalcLow  Label_433  // call via Call @UI_Update_Highlight__CalcLow or :UI_Update_Highlight__CalcLow
#define UI_Update_Highlight__Return  Label_434  // call via Call @UI_Update_Highlight__Return or :UI_Update_Highlight__Return
#define UI_Update_Highlight__CalcHigh  Label_435  // call via Call @UI_Update_Highlight__CalcHigh or :UI_Update_Highlight__CalcHigh
#define UI_Draw_HighlightSprite  Label_436  // call via Call @UI_Draw_HighlightSprite or :UI_Draw_HighlightSprite
#define UI_Draw_Highlight__EnabledBranch  Label_437  // call via Call @UI_Draw_Highlight__EnabledBranch or :UI_Draw_Highlight__EnabledBranch
#define UI_Draw_Highlight__DrawSelected  Label_438  // call via Call @UI_Draw_Highlight__DrawSelected or :UI_Draw_Highlight__DrawSelected
#define UI_Get_SelectionColor  Label_439  // call via Call @UI_Get_SelectionColor or :UI_Get_SelectionColor
#define UI_Draw_Highlight__DrawUnselected  Label_440  // call via Call @UI_Draw_Highlight__DrawUnselected or :UI_Draw_Highlight__DrawUnselected
#define Util_LangPick__English  Label_441  // call via Call @Util_LangPick__English or :Util_LangPick__English
#define Util_LangPick__Return  Label_442  // call via Call @Util_LangPick__Return or :Util_LangPick__Return
#define UI_Draw_IconPlus__CalcLow  Label_446  // call via Call @UI_Draw_IconPlus__CalcLow or :UI_Draw_IconPlus__CalcLow
#define UI_Draw_IconPlus__Return  Label_447  // call via Call @UI_Draw_IconPlus__Return or :UI_Draw_IconPlus__Return
#define UI_Draw_IconPlus__CalcHigh  Label_448  // call via Call @UI_Draw_IconPlus__CalcHigh or :UI_Draw_IconPlus__CalcHigh
#define UI_Draw_IconPlus__DrawIcon  Label_449  // call via Call @UI_Draw_IconPlus__DrawIcon or :UI_Draw_IconPlus__DrawIcon
#define Util_MakeButtonSpriteName  Label_450  // call via Call @Util_MakeButtonSpriteName or :Util_MakeButtonSpriteName
#define Util_EnsureTextureDict__AlreadyLoaded  Label_451  // call via Call @Util_EnsureTextureDict__AlreadyLoaded or :Util_EnsureTextureDict__AlreadyLoaded
#define UI_Draw_Sprite__AlreadyLoaded  Label_452  // call via Call @UI_Draw_Sprite__AlreadyLoaded or :UI_Draw_Sprite__AlreadyLoaded
#define Func_Label_453  Label_453  // call via Call @Func_Label_453 or :Func_Label_453
#define UI_Handle_MenuSelect__NotPressed  Label_454  // call via Call @UI_Handle_MenuSelect__NotPressed or :UI_Handle_MenuSelect__NotPressed
#define State_PushAndSetPage  Label_455  // call via Call @State_PushAndSetPage or :State_PushAndSetPage
#define Func_Label_456  Label_456  // call via Call @Func_Label_456 or :Func_Label_456
#define Page_StaticText_Label_458  Label_458  // call via Call @Page_StaticText_Label_458 or :Page_StaticText_Label_458
#define Func_Label_460  Label_460  // call via Call @Func_Label_460 or :Func_Label_460
#define Func_Label_461  Label_461  // call via Call @Func_Label_461 or :Func_Label_461
#define Func_Label_462  Label_462  // call via Call @Func_Label_462 or :Func_Label_462
#define Func_Label_463  Label_463  // call via Call @Func_Label_463 or :Func_Label_463
#define Func_Label_464  Label_464  // call via Call @Func_Label_464 or :Func_Label_464
#define Func_Label_466  Label_466  // call via Call @Func_Label_466 or :Func_Label_466
#define Func_Label_475  Label_475  // call via Call @Func_Label_475 or :Func_Label_475
#define Func_Label_481  Label_481  // call via Call @Func_Label_481 or :Func_Label_481
#define Func_Label_482  Label_482  // call via Call @Func_Label_482 or :Func_Label_482
#define Func_Label_483  Label_483  // call via Call @Func_Label_483 or :Func_Label_483
#define Func_Label_486  Label_486  // call via Call @Func_Label_486 or :Func_Label_486
#define Func_Label_487  Label_487  // call via Call @Func_Label_487 or :Func_Label_487
#define Func_Label_488  Label_488  // call via Call @Func_Label_488 or :Func_Label_488
#define Page_StaticText_Label_491  Label_491  // call via Call @Page_StaticText_Label_491 or :Page_StaticText_Label_491
#define Func_Label_497  Label_497  // call via Call @Func_Label_497 or :Func_Label_497
#define Tick_HandleInputAndQueue  Label_5  // call via Call @Tick_HandleInputAndQueue or :Tick_HandleInputAndQueue
#define Func_Label_500  Label_500  // call via Call @Func_Label_500 or :Func_Label_500
#define Func_Label_501  Label_501  // call via Call @Func_Label_501 or :Func_Label_501
#define Func_Label_512  Label_512  // call via Call @Func_Label_512 or :Func_Label_512
#define Func_Label_516  Label_516  // call via Call @Func_Label_516 or :Func_Label_516
#define Page_StaticText_Label_517  Label_517  // call via Call @Page_StaticText_Label_517 or :Page_StaticText_Label_517
#define Func_Label_518  Label_518  // call via Call @Func_Label_518 or :Func_Label_518
#define UI_Draw_TextRow_Internal  Label_546  // call via Call @UI_Draw_TextRow_Internal or :UI_Draw_TextRow_Internal
#define Func_Label_551  Label_551  // call via Call @Func_Label_551 or :Func_Label_551
#define Func_Label_552  Label_552  // call via Call @Func_Label_552 or :Func_Label_552
#define Page_StaticText_Label_554  Label_554  // call via Call @Page_StaticText_Label_554 or :Page_StaticText_Label_554
#define Func_Label_561  Label_561  // call via Call @Func_Label_561 or :Func_Label_561
#define Page_Splash_Impl  Label_58  // call via Call @Page_Splash_Impl or :Page_Splash_Impl
#define Tick_PrepareDrawAndProtections  Label_6  // call via Call @Tick_PrepareDrawAndProtections or :Tick_PrepareDrawAndProtections
#define Page_Language_Select  Label_60  // call via Call @Page_Language_Select or :Page_Language_Select
#define Func_Label_604  Label_604  // call via Call @Func_Label_604 or :Func_Label_604
#define Page_StaticText_Label_62  Label_62  // call via Call @Page_StaticText_Label_62 or :Page_StaticText_Label_62
#define Func_Label_633  Label_633  // call via Call @Func_Label_633 or :Func_Label_633
#define Page_ModsMenus_Impl  Label_64  // call via Call @Page_ModsMenus_Impl or :Page_ModsMenus_Impl
#define Page_Recovery_Impl  Label_65  // call via Call @Page_Recovery_Impl or :Page_Recovery_Impl
#define Page_Protections_Impl  Label_66  // call via Call @Page_Protections_Impl or :Page_Protections_Impl
#define Page_Outfits_Router  Label_67  // call via Call @Page_Outfits_Router or :Page_Outfits_Router
#define Page_Freezers_Impl  Label_68  // call via Call @Page_Freezers_Impl or :Page_Freezers_Impl
#define Page_Vehicles_Impl  Label_69  // call via Call @Page_Vehicles_Impl or :Page_Vehicles_Impl
#define Func_Label_690  Label_690  // call via Call @Func_Label_690 or :Func_Label_690
#define Page_Maps_Impl  Label_70  // call via Call @Page_Maps_Impl or :Page_Maps_Impl
#define Page_Misc_Impl  Label_71  // call via Call @Page_Misc_Impl or :Page_Misc_Impl
#define Page_Credits_Impl  Label_72  // call via Call @Page_Credits_Impl or :Page_Credits_Impl
#define Page_StaticText_Label_729  Label_729  // call via Call @Page_StaticText_Label_729 or :Page_StaticText_Label_729
#define Page_Animations_Impl  Label_73  // call via Call @Page_Animations_Impl or :Page_Animations_Impl
#define Page_Teleport_Hub_Impl  Label_74  // call via Call @Page_Teleport_Hub_Impl or :Page_Teleport_Hub_Impl
#define Page_StaticText_Label_745  Label_745  // call via Call @Page_StaticText_Label_745 or :Page_StaticText_Label_745
#define Page_SecretPlaces_Impl  Label_75  // call via Call @Page_SecretPlaces_Impl or :Page_SecretPlaces_Impl
#define Page_Interiors_Impl  Label_76  // call via Call @Page_Interiors_Impl or :Page_Interiors_Impl
#define Page_StaticText_Label_766  Label_766  // call via Call @Page_StaticText_Label_766 or :Page_StaticText_Label_766
#define Page_Infinite8_Impl  Label_77  // call via Call @Page_Infinite8_Impl or :Page_Infinite8_Impl
#define Page_UnderWater_Impl  Label_78  // call via Call @Page_UnderWater_Impl or :Page_UnderWater_Impl
#define Page_StaticText_Label_789  Label_789  // call via Call @Page_StaticText_Label_789 or :Page_StaticText_Label_789
#define Page_TgsaudoizMaps_Impl  Label_79  // call via Call @Page_TgsaudoizMaps_Impl or :Page_TgsaudoizMaps_Impl
#define Page_MenuCustomization_Impl  Label_80  // call via Call @Page_MenuCustomization_Impl or :Page_MenuCustomization_Impl
#define Page_StaticText_Label_807  Label_807  // call via Call @Page_StaticText_Label_807 or :Page_StaticText_Label_807
#define Page_MaleOutfits_List_Impl  Label_81  // call via Call @Page_MaleOutfits_List_Impl or :Page_MaleOutfits_List_Impl
#define Page_FemaleOutfits_List_Impl  Label_82  // call via Call @Page_FemaleOutfits_List_Impl or :Page_FemaleOutfits_List_Impl
#define Page_StaticText_Label_822  Label_822  // call via Call @Page_StaticText_Label_822 or :Page_StaticText_Label_822
#define Page_Settings_Root_Impl  Label_83  // call via Call @Page_Settings_Root_Impl or :Page_Settings_Root_Impl
#define Page_BuzzardOutfits_Detail_Impl  Label_84  // call via Call @Page_BuzzardOutfits_Detail_Impl or :Page_BuzzardOutfits_Detail_Impl
#define Page_StaticText_Label_842  Label_842  // call via Call @Page_StaticText_Label_842 or :Page_StaticText_Label_842
#define Page_PoWerPuffOutfits_Detail_Impl  Label_85  // call via Call @Page_PoWerPuffOutfits_Detail_Impl or :Page_PoWerPuffOutfits_Detail_Impl
#define Page_StaticText_Label_851  Label_851  // call via Call @Page_StaticText_Label_851 or :Page_StaticText_Label_851
#define Page_PlayerOptions_Router_Impl  Label_86  // call via Call @Page_PlayerOptions_Router_Impl or :Page_PlayerOptions_Router_Impl
#define Page_MenuEditor_Router_Impl  Label_87  // call via Call @Page_MenuEditor_Router_Impl or :Page_MenuEditor_Router_Impl
#define Page_StaticText_Label_876  Label_876  // call via Call @Page_StaticText_Label_876 or :Page_StaticText_Label_876
#define Page_Settings_Scrollbar3_Impl  Label_88  // call via Call @Page_Settings_Scrollbar3_Impl or :Page_Settings_Scrollbar3_Impl
#define Page_HudColorEditor_Impl  Label_89  // call via Call @Page_HudColorEditor_Impl or :Page_HudColorEditor_Impl
#define Page_StaticText_Label_898  Label_898  // call via Call @Page_StaticText_Label_898 or :Page_StaticText_Label_898
#define Draw_BackgroundIfMenuOpen  Label_9  // call via Call @Draw_BackgroundIfMenuOpen or :Draw_BackgroundIfMenuOpen
#define Page_Background_Impl  Label_90  // call via Call @Page_Background_Impl or :Page_Background_Impl
#define Page_Title_Impl  Label_91  // call via Call @Page_Title_Impl or :Page_Title_Impl
#define Page_StaticText_Label_916  Label_916  // call via Call @Page_StaticText_Label_916 or :Page_StaticText_Label_916
#define Page_Settings_Scrollbar1_Impl  Label_92  // call via Call @Page_Settings_Scrollbar1_Impl or :Page_Settings_Scrollbar1_Impl
#define Page_Settings_Scrollbar2_Impl  Label_93  // call via Call @Page_Settings_Scrollbar2_Impl or :Page_Settings_Scrollbar2_Impl
#define Page_SelectedText_Impl  Label_94  // call via Call @Page_SelectedText_Impl or :Page_SelectedText_Impl
#define Page_StaticText_Label_940  Label_940  // call via Call @Page_StaticText_Label_940 or :Page_StaticText_Label_940
#define Page_StaticText_Label_949  Label_949  // call via Call @Page_StaticText_Label_949 or :Page_StaticText_Label_949
#define Page_UnselectedText_Impl  Label_95  // call via Call @Page_UnselectedText_Impl or :Page_UnselectedText_Impl
#define Page_Protection_Modder_Impl  Label_96  // call via Call @Page_Protection_Modder_Impl or :Page_Protection_Modder_Impl
#define Page_StaticText_Label_969  Label_969  // call via Call @Page_StaticText_Label_969 or :Page_StaticText_Label_969
#define Page_SAAB_Outfits_A_Impl  Label_97  // call via Call @Page_SAAB_Outfits_A_Impl or :Page_SAAB_Outfits_A_Impl
#define Page_StaticText_Label_979  Label_979  // call via Call @Page_StaticText_Label_979 or :Page_StaticText_Label_979
#define Page_JakeModz_Outfits_A_Impl  Label_98  // call via Call @Page_JakeModz_Outfits_A_Impl or :Page_JakeModz_Outfits_A_Impl
#define Page_SAAB_Outfits_B_Impl  Label_99  // call via Call @Page_SAAB_Outfits_B_Impl or :Page_SAAB_Outfits_B_Impl
#define Page_StaticText_Label_999  Label_999  // call via Call @Page_StaticText_Label_999 or :Page_StaticText_Label_999
#define Func_UnusedFunction_0  UnusedFunction_0  // call via Call @Func_UnusedFunction_0 or :Func_UnusedFunction_0
#define Func_UnusedFunction_1  UnusedFunction_1  // call via Call @Func_UnusedFunction_1 or :Func_UnusedFunction_1
#define Func_UnusedFunction_2  UnusedFunction_2  // call via Call @Func_UnusedFunction_2 or :Func_UnusedFunction_2
#define Func_UnusedFunction_3  UnusedFunction_3  // call via Call @Func_UnusedFunction_3 or :Func_UnusedFunction_3
#define Func_UnusedFunction_4  UnusedFunction_4  // call via Call @Func_UnusedFunction_4 or :Func_UnusedFunction_4
#define Func_UnusedFunction_5  UnusedFunction_5  // call via Call @Func_UnusedFunction_5 or :Func_UnusedFunction_5
#define Func_UnusedFunction_6  UnusedFunction_6  // call via Call @Func_UnusedFunction_6 or :Func_UnusedFunction_6
#define Func_UnusedFunction_7  UnusedFunction_7  // call via Call @Func_UnusedFunction_7 or :Func_UnusedFunction_7
#define Func_UnusedFunction_8  UnusedFunction_8  // call via Call @Func_UnusedFunction_8 or :Func_UnusedFunction_8
#define Func_UnusedFunction_9  UnusedFunction_9  // call via Call @Func_UnusedFunction_9 or :Func_UnusedFunction_9

// ---------- Static1 (512) ----------
#define gMenu_X  Static1[0]  // StaticSet1/StaticGet1 0
#define gMenu_Y  Static1[1]  // StaticSet1/StaticGet1 1
#define gMenu_W  Static1[2]  // StaticSet1/StaticGet1 2
#define gTheme_HudId_Primary  Static1[3]  // StaticSet1/StaticGet1 3
#define gTheme_HudId_Secondary  Static1[4]  // StaticSet1/StaticGet1 4
#define gTheme_HudId_Tertiary  Static1[5]  // StaticSet1/StaticGet1 5
#define gTheme_HudId_Accent  Static1[6]  // StaticSet1/StaticGet1 6
#define gTheme_HudId_Background  Static1[7]  // StaticSet1/StaticGet1 7
#define gTheme_HudId_A  Static1[8]  // StaticSet1/StaticGet1 8
#define gTheme_HudId_B  Static1[9]  // StaticSet1/StaticGet1 9
#define gTheme_HudId_C  Static1[10]  // StaticSet1/StaticGet1 10
#define gTheme_HudId_D  Static1[11]  // StaticSet1/StaticGet1 11
#define gTheme_HudId_E  Static1[12]  // StaticSet1/StaticGet1 12
#define gTheme_HudId_F  Static1[13]  // StaticSet1/StaticGet1 13
#define gTheme_HudId_Green  Static1[14]  // StaticSet1/StaticGet1 14
#define gTheme_HudId_Yellow  Static1[15]  // StaticSet1/StaticGet1 15
#define gTheme_HudId_Orange  Static1[16]  // StaticSet1/StaticGet1 16
#define gTheme_HudId_H  Static1[17]  // StaticSet1/StaticGet1 17
#define gTheme_HudId_I  Static1[18]  // StaticSet1/StaticGet1 18
#define gTheme_HudId_J  Static1[19]  // StaticSet1/StaticGet1 19
#define gTheme_HudId_K  Static1[20]  // StaticSet1/StaticGet1 20
#define gTheme_HudId_L  Static1[21]  // StaticSet1/StaticGet1 21
#define gTheme_HudId_M  Static1[22]  // StaticSet1/StaticGet1 22
#define gTheme_HudId_N  Static1[23]  // StaticSet1/StaticGet1 23
#define gTheme_HudId_Selected  Static1[24]  // StaticSet1/StaticGet1 24
#define gTheme_HudId_Unselected  Static1[25]  // StaticSet1/StaticGet1 25
#define gTheme_HudId_Title  Static1[26]  // StaticSet1/StaticGet1 26
#define gTheme_HudId_Title2  Static1[27]  // StaticSet1/StaticGet1 27
#define gToggle_DisabledFlag  Static1[28]  // StaticSet1/StaticGet1 28
#define gAlpha_Global  Static1[29]  // StaticSet1/StaticGet1 29
#define gSafeZone_Multiplier  Static1[30]  // StaticSet1/StaticGet1 30
#define gColor_R_White  Static1[31]  // StaticSet1/StaticGet1 31
#define gColor_G_White  Static1[32]  // StaticSet1/StaticGet1 32
#define gColor_B_White  Static1[33]  // StaticSet1/StaticGet1 33
#define gColor_A_White  Static1[34]  // StaticSet1/StaticGet1 34
#define gColor_R_Select  Static1[35]  // StaticSet1/StaticGet1 35
#define gColor_G_Select  Static1[36]  // StaticSet1/StaticGet1 36
#define gColor_B_Select  Static1[37]  // StaticSet1/StaticGet1 37
#define gColor_R_Background  Static1[38]  // StaticSet1/StaticGet1 38
#define gColor_G_Background  Static1[39]  // StaticSet1/StaticGet1 39
#define gColor_B_Background  Static1[40]  // StaticSet1/StaticGet1 40
#define gColor_A_Background  Static1[41]  // StaticSet1/StaticGet1 41
#define gColor_R_Title  Static1[42]  // StaticSet1/StaticGet1 42
#define gColor_R_Shadow  Static1[43]  // StaticSet1/StaticGet1 43
#define gColor_G_Shadow  Static1[44]  // StaticSet1/StaticGet1 44
#define gColor_Scroll_R  Static1[45]  // StaticSet1/StaticGet1 45
#define gColor_Scroll_G  Static1[46]  // StaticSet1/StaticGet1 46
#define gColor_Scroll_B  Static1[47]  // StaticSet1/StaticGet1 47
#define gColor_Row_R  Static1[48]  // StaticSet1/StaticGet1 48
#define gColor_Row_G  Static1[49]  // StaticSet1/StaticGet1 49
#define gColor_Row_B  Static1[50]  // StaticSet1/StaticGet1 50
#define gColor_Row_A  Static1[51]  // StaticSet1/StaticGet1 51
#define gColor_Border_R  Static1[52]  // StaticSet1/StaticGet1 52
#define gColor_Border_G  Static1[53]  // StaticSet1/StaticGet1 53
#define gColor_Border_B  Static1[54]  // StaticSet1/StaticGet1 54
#define gColor_Border_A  Static1[55]  // StaticSet1/StaticGet1 55
#define gColor_Header_R  Static1[56]  // StaticSet1/StaticGet1 56
#define gColor_Header_G  Static1[57]  // StaticSet1/StaticGet1 57
#define gColor_Header_B  Static1[58]  // StaticSet1/StaticGet1 58
#define gColor_Header_A  Static1[59]  // StaticSet1/StaticGet1 59
#define gColor_TextUnselected_R  Static1[60]  // StaticSet1/StaticGet1 60
#define gColor_TextUnselected_G  Static1[61]  // StaticSet1/StaticGet1 61
#define gColor_TextUnselected_B  Static1[62]  // StaticSet1/StaticGet1 62
#define gColor_TextSelected_R  Static1[63]  // StaticSet1/StaticGet1 63
#define gColor_TextSelected_G  Static1[64]  // StaticSet1/StaticGet1 64
#define gColor_TextSelected_B  Static1[65]  // StaticSet1/StaticGet1 65
#define gColor_Icon_R  Static1[66]  // StaticSet1/StaticGet1 66
#define gColor_Icon_G  Static1[67]  // StaticSet1/StaticGet1 67
#define gColor_Icon_B  Static1[68]  // StaticSet1/StaticGet1 68
#define gColor_Icon_A  Static1[69]  // StaticSet1/StaticGet1 69
#define gLanguage  Static1[70]  // StaticSet1/StaticGet1 70
#define gFlags_Main  Static1[71]  // StaticSet1/StaticGet1 71
#define gFlags_Player  Static1[72]  // StaticSet1/StaticGet1 72
#define gFlags_Recovery  Static1[73]  // StaticSet1/StaticGet1 73
#define gMenu_TmpIsVisible  Static1[74]  // StaticSet1/StaticGet1 74
#define gMenu_PrevState  Static1[75]  // StaticSet1/StaticGet1 75
#define gMenu_IsTransitioning  Static1[76]  // StaticSet1/StaticGet1 76
#define gMenu_FadeAlpha  Static1[77]  // StaticSet1/StaticGet1 77
#define gMenu_ScrollOffsetY  Static1[78]  // StaticSet1/StaticGet1 78
#define gMenu_NeedsRedraw  Static1[79]  // StaticSet1/StaticGet1 79
#define gMenu_ForceRefresh  Static1[80]  // StaticSet1/StaticGet1 80
#define gMenu_PageStackDepth  Static1[81]  // StaticSet1/StaticGet1 81
#define gMenu_SelectedColorId  Static1[82]  // StaticSet1/StaticGet1 82
#define gMenu_UnselectedColorId  Static1[83]  // StaticSet1/StaticGet1 83
#define gMenu_TitleColorId  Static1[84]  // StaticSet1/StaticGet1 84
#define gMenu_HeaderColorId  Static1[85]  // StaticSet1/StaticGet1 85
#define gMenu_FooterColorId  Static1[86]  // StaticSet1/StaticGet1 86
#define gMenu_BorderColorId  Static1[87]  // StaticSet1/StaticGet1 87
#define gMenu_ToggleOnColor  Static1[88]  // StaticSet1/StaticGet1 88
#define gMenu_ToggleOffColor  Static1[89]  // StaticSet1/StaticGet1 89
#define gMenu_DisabledColor  Static1[90]  // StaticSet1/StaticGet1 90
#define gMenu_HighlightAlpha  Static1[91]  // StaticSet1/StaticGet1 91
#define gSfx_Enabled  Static1[92]  // StaticSet1/StaticGet1 92
#define gInput_HoldTimer  Static1[93]  // StaticSet1/StaticGet1 93
#define gUnk1_94  Static1[94]  // StaticSet1/StaticGet1 94
#define gUnk1_95  Static1[95]  // StaticSet1/StaticGet1 95
#define gUnk1_96  Static1[96]  // StaticSet1/StaticGet1 96
#define gUnk1_97  Static1[97]  // StaticSet1/StaticGet1 97
#define gUnk1_98  Static1[98]  // StaticSet1/StaticGet1 98
#define gUnk1_99  Static1[99]  // StaticSet1/StaticGet1 99
#define gUI_RowHeight  Static1[100]  // StaticSet1/StaticGet1 100
#define gUI_TmpCounter  Static1[101]  // StaticSet1/StaticGet1 101
#define gUI_WrapMode  Static1[102]  // StaticSet1/StaticGet1 102
#define gUI_ScaleX  Static1[103]  // StaticSet1/StaticGet1 103
#define gUI_ScaleY  Static1[104]  // StaticSet1/StaticGet1 104
#define gUI_MaxRows  Static1[105]  // StaticSet1/StaticGet1 105
#define gUI_TextSizeSmall  Static1[106]  // StaticSet1/StaticGet1 106
#define gUI_TextSizeMedium  Static1[107]  // StaticSet1/StaticGet1 107
#define gUI_TextSizeLarge  Static1[108]  // StaticSet1/StaticGet1 108
#define gUI_HeaderHeight  Static1[109]  // StaticSet1/StaticGet1 109
#define gUI_FooterHeight  Static1[110]  // StaticSet1/StaticGet1 110
#define gUI_Padding  Static1[111]  // StaticSet1/StaticGet1 111
#define gUI_Margin  Static1[112]  // StaticSet1/StaticGet1 112
#define gUI_BorderWidth  Static1[113]  // StaticSet1/StaticGet1 113
#define gUI_ShadowOffset  Static1[114]  // StaticSet1/StaticGet1 114
#define gUI_IconSize  Static1[115]  // StaticSet1/StaticGet1 115
#define gUI_AnimationSpeed  Static1[116]  // StaticSet1/StaticGet1 116
#define gUI_FadeSpeed  Static1[117]  // StaticSet1/StaticGet1 117
#define gUI_ScrollSpeed  Static1[118]  // StaticSet1/StaticGet1 118
#define gUI_SoundVolume  Static1[119]  // StaticSet1/StaticGet1 119
#define gVehicle_SelectedCategory  Static1[120]  // StaticSet1/StaticGet1 120
#define gVehicle_SelectedModelIdx  Static1[121]  // StaticSet1/StaticGet1 121
#define gVehicle_SelectedColorIdx  Static1[122]  // StaticSet1/StaticGet1 122
#define gVehicle_SelectedModIdx  Static1[123]  // StaticSet1/StaticGet1 123
#define gVehicle_SpawnDistance  Static1[124]  // StaticSet1/StaticGet1 124
#define gVehicle_SpawnHeading  Static1[125]  // StaticSet1/StaticGet1 125
#define gVehicle_UseGroundProperly  Static1[126]  // StaticSet1/StaticGet1 126
#define gVehicle_AutoFix  Static1[127]  // StaticSet1/StaticGet1 127
#define gVehicle_TmpHandle  Static1[128]  // StaticSet1/StaticGet1 128
#define gTick_LastFrame  Static1[129]  // StaticSet1/StaticGet1 129
#define gMenu_CurrentState  Static1[130]  // StaticSet1/StaticGet1 130
#define gTick_NextInputAllowedTime  Static1[131]  // StaticSet1/StaticGet1 131
#define gMenu_ScrollSpeedRaw  Static1[132]  // StaticSet1/StaticGet1 132
#define gMenu_ScrollDir  Static1[133]  // StaticSet1/StaticGet1 133
#define gQueue_PendingScript  Static1[134]  // StaticSet1/StaticGet1 134
#define gQueue_RequestSent  Static1[135]  // StaticSet1/StaticGet1 135
#define gQueue_PendingStack  Static1[136]  // StaticSet1/StaticGet1 136
#define gProt_FxClearFlags  Static1[137]  // StaticSet1/StaticGet1 137
#define gProt_PlayerFlags  Static1[138]  // StaticSet1/StaticGet1 138
#define gProt_GlobalFlags  Static1[139]  // StaticSet1/StaticGet1 139
#define gUI_Unk_140  Static1[140]  // StaticSet1/StaticGet1 140
#define gQueue_Head  Static1[141]  // StaticSet1/StaticGet1 141
#define gQueue_Tail  Static1[142]  // StaticSet1/StaticGet1 142
#define gProt_RemoteFlags  Static1[143]  // StaticSet1/StaticGet1 143
#define gMenu_StackSizeOverride  Static1[144]  // StaticSet1/StaticGet1 144
#define gCheat_FastKillFlags  Static1[145]  // StaticSet1/StaticGet1 145
#define gMenu_AnimFlags  Static1[146]  // StaticSet1/StaticGet1 146
#define gProt_VehicleFlags  Static1[147]  // StaticSet1/StaticGet1 147
#define gUI_Unk_148  Static1[148]  // StaticSet1/StaticGet1 148
#define gUI_Unk_149  Static1[149]  // StaticSet1/StaticGet1 149
#define gFeature_UseVNextQueue  Static1[150]  // StaticSet1/StaticGet1 150
#define gPlayer_WantedLevelBackup  Static1[151]  // StaticSet1/StaticGet1 151
#define gUI_Unk_152  Static1[152]  // StaticSet1/StaticGet1 152
#define gPlayer_GodModeCached  Static1[153]  // StaticSet1/StaticGet1 153
#define gUI_Unk_155  Static1[155]  // StaticSet1/StaticGet1 155
#define gUI_Unk_157  Static1[157]  // StaticSet1/StaticGet1 157
#define gUI_Unk_159  Static1[159]  // StaticSet1/StaticGet1 159
#define gUI_Unk_160  Static1[160]  // StaticSet1/StaticGet1 160
#define gVehicle_GravityFlags  Static1[162]  // StaticSet1/StaticGet1 162
#define gUI_Unk_163  Static1[163]  // StaticSet1/StaticGet1 163
#define gUI_Unk_165  Static1[165]  // StaticSet1/StaticGet1 165
#define gUI_Unk_166  Static1[166]  // StaticSet1/StaticGet1 166
#define gProt_SpawnFlags  Static1[167]  // StaticSet1/StaticGet1 167
#define gProt_NetworkFlags  Static1[168]  // StaticSet1/StaticGet1 168
#define gUI_Unk_169  Static1[169]  // StaticSet1/StaticGet1 169
#define gUI_Unk_170  Static1[170]  // StaticSet1/StaticGet1 170
#define gUI_Unk_171  Static1[171]  // StaticSet1/StaticGet1 171
#define gUI_Unk_172  Static1[172]  // StaticSet1/StaticGet1 172
#define gMenu_PageHistoryDepth  Static1[173]  // StaticSet1/StaticGet1 173
#define gMenu_HistoryTop  Static1[174]  // StaticSet1/StaticGet1 174
#define gTheme_Custom_R1  Static1[175]  // StaticSet1/StaticGet1 175
#define gTheme_Custom_R2  Static1[186]  // StaticSet1/StaticGet1 186
#define gInput_SelectedIndex  Static1[197]  // StaticSet1/StaticGet1 197
#define gUI_VisibleCount  Static1[198]  // StaticSet1/StaticGet1 198
#define gUnk1_199  Static1[199]  // StaticSet1/StaticGet1 199
#define gUnk1_200  Static1[200]  // StaticSet1/StaticGet1 200
#define gUnk1_201  Static1[201]  // StaticSet1/StaticGet1 201
#define gUnk1_202  Static1[202]  // StaticSet1/StaticGet1 202
#define gTheme_PaletteId  Static1[203]  // StaticSet1/StaticGet1 203
#define gTheme_Handle1  Static1[204]  // StaticSet1/StaticGet1 204
#define gTheme_Handle2  Static1[205]  // StaticSet1/StaticGet1 205
#define gUnk1_206  Static1[206]  // StaticSet1/StaticGet1 206
#define gUnk1_207  Static1[207]  // StaticSet1/StaticGet1 207
#define gUnk1_208  Static1[208]  // StaticSet1/StaticGet1 208
#define gUI_Hdr_R  Static1[209]  // StaticSet1/StaticGet1 209
#define gUI_Hdr_G  Static1[210]  // StaticSet1/StaticGet1 210
#define gUI_Hdr_B  Static1[211]  // StaticSet1/StaticGet1 211
#define gUI_Hdr_A  Static1[212]  // StaticSet1/StaticGet1 212
#define gUI_TextBaseY  Static1[213]  // StaticSet1/StaticGet1 213
#define gUI_CursorY  Static1[214]  // StaticSet1/StaticGet1 214
#define gUnk1_215  Static1[215]  // StaticSet1/StaticGet1 215
#define gUnk1_216  Static1[216]  // StaticSet1/StaticGet1 216
#define gUnk1_217  Static1[217]  // StaticSet1/StaticGet1 217
#define gUnk1_218  Static1[218]  // StaticSet1/StaticGet1 218
#define gUnk1_219  Static1[219]  // StaticSet1/StaticGet1 219
#define gUnk1_220  Static1[220]  // StaticSet1/StaticGet1 220
#define gUnk1_221  Static1[221]  // StaticSet1/StaticGet1 221
#define gUnk1_222  Static1[222]  // StaticSet1/StaticGet1 222
#define gUI_MaxVisibleRows  Static1[223]  // StaticSet1/StaticGet1 223
#define gUI_HighlightX  Static1[224]  // StaticSet1/StaticGet1 224
#define gUI_ShowBorders  Static1[225]  // StaticSet1/StaticGet1 225
#define gUnk1_226  Static1[226]  // StaticSet1/StaticGet1 226
#define gUI_SpriteW_Selected  Static1[227]  // StaticSet1/StaticGet1 227
#define gUI_SpriteH_Selected  Static1[228]  // StaticSet1/StaticGet1 228
#define gUI_ColR_Selected  Static1[229]  // StaticSet1/StaticGet1 229
#define gUI_ColG_Selected  Static1[230]  // StaticSet1/StaticGet1 230
#define gUI_ColB_Selected  Static1[231]  // StaticSet1/StaticGet1 231
#define gUI_SpriteW_Normal  Static1[232]  // StaticSet1/StaticGet1 232
#define gUI_SpriteH_Normal  Static1[233]  // StaticSet1/StaticGet1 233
#define gUI_ColR_Normal  Static1[234]  // StaticSet1/StaticGet1 234
#define gUI_ColG_Normal  Static1[235]  // StaticSet1/StaticGet1 235
#define gUI_ColB_Normal  Static1[236]  // StaticSet1/StaticGet1 236
#define gUnk1_237  Static1[237]  // StaticSet1/StaticGet1 237
#define gUI_ColR_SpriteOn  Static1[238]  // StaticSet1/StaticGet1 238
#define gUI_ColG_SpriteOn  Static1[239]  // StaticSet1/StaticGet1 239
#define gUI_ColB_SpriteOn  Static1[240]  // StaticSet1/StaticGet1 240
#define gUI_BG_R  Static1[241]  // StaticSet1/StaticGet1 241
#define gUI_BG_G  Static1[242]  // StaticSet1/StaticGet1 242
#define gUI_BG_B  Static1[243]  // StaticSet1/StaticGet1 243
#define gUnk1_244  Static1[244]  // StaticSet1/StaticGet1 244
#define gUnk1_245  Static1[245]  // StaticSet1/StaticGet1 245
#define gUnk1_246  Static1[246]  // StaticSet1/StaticGet1 246
#define gUI_FG_R  Static1[247]  // StaticSet1/StaticGet1 247
#define gUI_FG_G  Static1[248]  // StaticSet1/StaticGet1 248
#define gUI_FG_B  Static1[249]  // StaticSet1/StaticGet1 249
#define gUnk1_250  Static1[250]  // StaticSet1/StaticGet1 250
#define gUnk1_251  Static1[251]  // StaticSet1/StaticGet1 251
#define gUnk1_252  Static1[252]  // StaticSet1/StaticGet1 252
#define gOutfit_CurrentIdx  Static1[253]  // StaticSet1/StaticGet1 253
#define gUnk1_254  Static1[254]  // StaticSet1/StaticGet1 254
#define gUnk1_255  Static1[255]  // StaticSet1/StaticGet1 255
#define gOutfit_Filter_Show  Static1[257]  // StaticSet1/StaticGet1 257
#define gOutfit_Scroll_R  Static1[258]  // StaticSet1/StaticGet1 258
#define gOutfit_Scroll_G  Static1[259]  // StaticSet1/StaticGet1 259
#define gOutfit_Scroll_B  Static1[260]  // StaticSet1/StaticGet1 260
#define gOutfit_PreviewEnabled  Static1[262]  // StaticSet1/StaticGet1 262
#define gText_R_Selected  Static1[268]  // StaticSet1/StaticGet1 268
#define gText_G_Selected  Static1[269]  // StaticSet1/StaticGet1 269
#define gText_B_Selected  Static1[270]  // StaticSet1/StaticGet1 270

// ---------- Static2 (600) ----------
#define gUnk2_256  Static2[256]
#define gUnk2_257  Static2[257]
#define gUnk2_258  Static2[258]
#define gUnk2_259  Static2[259]
#define gUnk2_260  Static2[260]
#define gUnk2_261  Static2[261]
#define gUnk2_262  Static2[262]
#define gUnk2_263  Static2[263]
#define gUnk2_264  Static2[264]
#define gUnk2_265  Static2[265]
#define gSprite_Width  Static2[266]
#define gSprite_Height  Static2[267]
#define gUnk2_268  Static2[268]
#define gUnk2_269  Static2[269]
#define gUnk2_270  Static2[270]
#define gUnk2_351  Static2[351]
#define gUnk2_352  Static2[352]
#define gTexDict_Punisher  Static2[353]
#define gTexDict_GlobeBG  Static2[354]
#define gTexDict_GlobeOffsetX  Static2[355]
#define gTexDict_Globe  Static2[356]
#define gLang_IsEnglish  Static2[357]
#define gUI_TextY  Static2[358]
#define gTmp_BufferPtrForButtonName  Static2[359]
#define gUI_TextWrap  Static2[362]
#define gUnk2_363  Static2[363]
#define gUI_RowColorSetA_R  Static2[364]
#define gUI_RowColorSetA_G  Static2[365]
#define gUI_RowColorSetA_B  Static2[366]
#define gUI_RowColorSetB_R  Static2[367]
#define gUI_RowColorSetB_G  Static2[368]
#define gUI_RowColorSetB_B  Static2[369]
#define gUI_RowColorSetC_R  Static2[370]
#define gUI_ScrollbarId1  Static2[371]
#define gUI_ScrollbarId2  Static2[372]
#define gUI_SpriteToggleEnabled  Static2[373]
#define gArray_Unk_374  Static2[374]
#define gArray_Unk_375  Static2[375]
#define gArray_Unk_376  Static2[376]
#define gUI_ScaleformHandle  Static2[377]
#define gArray_Unk_378  Static2[378]
#define gArray_Unk_379  Static2[379]
#define gArray_Unk_380  Static2[380]
#define gAnim_WasSelected  Static2[391]
#define gAnim_Looped  Static2[392]
#define gAnim_UpperOnly  Static2[393]
#define gAnim_AllowMove  Static2[394]
#define gAnim_Contorted  Static2[395]
#define gNet_PlayerActiveCheck  Static2[396]
#define gArray_OutfitCache_R  Static2[397]
#define gArray_OutfitCache_G  Static2[398]
#define gArray_OutfitCache_B  Static2[399]
#define gArray_Unk_400  Static2[400]
#define gArray_VehicleCache_A  Static2[401]
#define gArray_VehicleCache_B  Static2[402]
#define gArray_VehicleCache_C  Static2[403]
#define gArray_VehicleCache_D  Static2[404]
#define gArray_VehicleCache_E  Static2[405]
#define gArray_Unk_406  Static2[406]
#define gArray_Unk_407  Static2[407]
#define gArray_Unk_409  Static2[409]
#define gNet_IsSessionHost  Static2[410]
#define gProt_PlayerListCache  Static2[411]
#define gUnk2_412  Static2[412]
#define gUnk2_413  Static2[413]
#define gUnk2_414  Static2[414]
#define gUnk2_415  Static2[415]
#define gUnk2_416  Static2[416]
#define gUnk2_417  Static2[417]
#define gUnk2_418  Static2[418]
#define gTmp_StrBuffer_100  Static2[420]
#define gQueue_ScriptSlot0  Static2[434]
#define gQueue_StackSlot0  Static2[438]
#define gQueue_VersionSlot0  Static2[442]
#define gQueue_StartTime  Static2[450]
#define gFav_Bitset  Static2[460]
